-- Additional users
CREATE ROLE "user" WITH LOGIN PASSWORD 'root' CREATEDB SUPERUSER;

CREATE DATABASE test OWNER "user" ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE test TO "user";

CREATE DATABASE try OWNER "user" ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE try TO "user";
